apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  # - imageName: localhost:5000/skaffold-helm
  #   workspace: ./containers/skaffold-helm
  # - imageName: localhost:5000/api-server
  #   workspace: ./containers/api-server
  - imageName: localhost:5000/leeroy-web
    workspace: ./containers/leeroy-web/
  - imageName: localhost:5000/leeroy-app
    workspace: ./containers/leeroy-app/
deploy:
#    helm:
#      releases:
#      - name: skaffold-helm
#        chartPath: ./charts/skaffold-helm
# #       #wait: true
# #       #valuesFilePath: helm-skaffold-values.yaml
#        values:
#          image: localhost:5000/skaffold-helm
# #       #overrides builds an override values.yaml file to run with the helm deploy
# #       #overrides:
# #       # some:
# #       #   key: someValue
# #       #setValues get appended to the helm deploy with --set.  
# #       #setValues:
# #         #some.key: someValue
#      - name: skaffold-helm
#        chartPath: ./charts/api-server
#        values:
#          image: localhost:5000/api-server
  kubectl:
    manifests:
    - ./containers/leeroy-web/kubernetes/*
    - ./containers/leeroy-app/kubernetes/*